motds:
  - "&ea rubber room with a singular rat"
  - "&eIm so lonely"
  - "&ewhat did someone steal your sweet roll?"
  - "&ewhat rhymes with hug me?"
  - "&ehen tie or smth"
  - "&eShitBob?"
  - "&eCrazy?"
  - "&eWhat are you crying?"
  - "&eYou already know what time it is"
  - "&eEat shit asshole, fall of your horse"
  - "&eLike an abuisive relationship"
  - "&eAn Aternos server"
  - "&efurry nigga ass"
  - "&eWhat did Osama do wrong?"
  - "&eA 2b2t Clone"
  - "&eFAGGOT!"
  - "&e/kill yourself (wittawwawy)"
  - "&eJOIN. BUILD. SUFFER. LEAVE"
  - "&e&3Just like 2b2t. &cBut mentally ill"
  - "&c2b2t is dead. &f10b10t killed it and fucked the corpse."
  - "&fYour base will burn. Your logs will be read. &cSmile for the audit."
  - "&eAbandon hope, ye who play here."
  - "&eblackcatsneaky56 is the owner"
  - "&eAn SMP server"
  - "&eswiftesz is the best player (hes not a swifte)"
  - "&eX: -67676 Z: 67676"
  - "&eas_s loves you :heart:"
  - "&eAn LGBT smp"
  - "&eFernando exists in a pocket dimension"
  - "&ehow do i make donkeys fuck again? -BeetenMC"
  - "&ereal men dont rape? oh shit must have been toast then."
  - "&cFORTNITE BALLS IM GAY I LIKE BOYS LIL MOSEY IS WHITE"
  - "&eTOAST, HELP! LAZ IS STUCK ON THE ROOF AGAIN!"
  - "&eSevere miscount"
  - "&ecell wall simplicity player versus player"
  - "&eyoutube watch?v=dQw4w9WgXcQ&list=RDdQw4w9WgXcQ&start_radio=1"
  - "&eBart more like Fart"
  - "&ewheres the original highway crew"
  - "&eAiden is a tranny"
  - "&egrief this, bitch!"
  - "&eThe Youngest Anarchy Server, EVER! - fitmc"
  - "&elet me get uhhhhhhhhhh"
  - "&esoek eats sand"
  - "&ci have no idea bruh"
  - "&elike 2b2t but just a bit more soft spoken"
  - "&eslow children at play"
  - "&eali has a hot sister"
  - "&e808 mafia"
  - "&eThe F students are invetors"
  - "&c No /tpa no /sethome just pure gay sex"
  - "&e?kit"
  - "&enonprofit weed factory"
  - "&eall donations go towards toasted avacodos addiction to marijauana"
  - "&edont feed the griefers"
  - "&4Repetition is the father of learning."
  - "&eIs Fit innocent?"
  - "&eStay."
  - "&eYe - HH"
  - "&eYe - Cousins"
  - "&eTry the cactus dupe."
