motds:
    - "<yellow>a rubber room with a singular rat"
    - "<yellow>Im so lonely"
    - "<yellow>what did someone steal your sweet roll?"
    - "<yellow>what rhymes with hug me?"
    - "<yellow>hen tie or smth"
    - "<yellow>ShitBob?"
    - "<yellow>Crazy?"
    - "<yellow>What are you crying?"
    - "<yellow>You already know what time it is"
    - "<yellow>Eat shit asshole, fall of your horse"
    - "<yellow>Like an abuisive relationship"
    - "<yellow>An Aternos server"
    - "<yellow>furry nigga ass"
    - "<yellow>What did Osama do wrong?"
    - "<yellow>A 2b2t Clone"
    - "<yellow>FAGGOT!"
    - "<yellow>/kill yourself (wittawwawy)"
    - "<yellow>JOIN. BUILD. SUFFER. LEAVE"
    - "<dark_aqua>Just like 2b2t. <red>But mentally ill"
    - "<red>2b2t is dead. <white>10b10t killed it and fucked the corpse."
    - "<white>Your base will burn. Your logs will be read. <red>Smile for the audit."
    - "<yellow>Abandon hope, ye who play here."
    - "<yellow>blackcatsneaky56 is the owner"
    - "<yellow>An SMP server"
    - "<yellow>swiftesz is the best player (hes not a swifte)"
    - "<yellow>X: -67676 Z: 67676"
    - "<yellow>as_s loves you :heart:"
    - "<yellow>An LGBT smp"
    - "<yellow>Fernando exists in a pocket dimension"
    - "<yellow>how do i make donkeys fuck again? -BeetenMC"
    - "<yellow>real men dont rape? oh shit must have been toast then."
    - "<red>FORTNITE BALLS IM GAY I LIKE BOYS LIL MOSEY IS WHITE"
    - "<yellow>TOAST, HELP! LAZ IS STUCK ON THE ROOF AGAIN!"
    - "<yellow>Severe miscount"
    - "<yellow>cell wall simplicity player versus player"
    - "<yellow>youtube watch?v=dQw4w9WgXcQ&list=RDdQw4w9WgXcQ&start_radio=1"
    - "<yellow>Bart more like Fart"
    - "<yellow>wheres the original highway crew"
    - "<yellow>Aiden is a tranny"
    - "<yellow>grief this, bitch!"
    - "<yellow>The Youngest Anarchy Server, EVER! - fitmc"
    - "<yellow>let me get uhhhhhhhhhh"
    - "<yellow>soek eats sand"
    - "<red>i have no idea bruh"
    - "<yellow>like 2b2t but just a bit more soft spoken"
    - "<yellow>slow children at play"
    - "<yellow>ali has a hot sister"
    - "<yellow>808 mafia"
    - "<yellow>The F students are invetors"
    - "<red> No /tpa no /sethome just pure gay sex"
    - "<yellow>?kit"
    - "<yellow>nonprofit weed factory"
    - "<yellow>all donations go towards toasted avacodos addiction to marijauana"
    - "<yellow>dont feed the griefers"
    - "<dark_red>Repetition is the father of learning."
    - "<yellow>Is Fit innocent?"
    - "<yellow>Stay."
    - "<yellow>Ye - HH"
    - "<yellow>Ye - Cousins"
    - "<yellow>Try the cactus dupe."
    - "<yellow>Do Not Fuck The Animals, Thank You!"
    
