text:
    - "<blue><bold><italic>10B <reset><yellow>a rubber room with a singular rat <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Im so lonely <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>what did someone steal your sweet roll? <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>what rhymes with hug me? <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>hen tie or smth <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>ShitBob? <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Crazy? <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>What are you crying? <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>You already know what time it is <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Eat shit asshole, fall of your horse <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Like an abuisive relationship <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>An Aternos server <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>furry nigga ass <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>What did Osama do wrong? <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>A 2b2t Clone <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>FAGGOT! <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>/kill yourself (wittawwawy) <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>JOIN. BUILD. SUFFER. LEAVE <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><dark_aqua>Just like 2b2t. <red>But mentally ill <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><red>2b2t is dead. <white>10b10t killed it and fucked the corpse. <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><white>Your base will burn. Your logs will be read. <red>Smile for the audit. <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Abandon hope, ye who play here. <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>blackcatsneaky56 is the owner <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>An SMP server <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>swiftesz is the best player (hes not a swifte) <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>X: -67676 Z: 67676 <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>as_s loves you :heart: <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>An LGBT smp <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Fernando exists in a pocket dimension <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>how do i make donkeys fuck again? -BeetenMC <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>real men dont rape? oh shit must have been toast then. <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><red>FORTNITE BALLS IM GAY I LIKE BOYS LIL MOSEY IS WHITE <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>TOAST, HELP! LAZ IS STUCK ON THE ROOF AGAIN! <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Severe miscount <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>cell wall simplicity player versus player <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>youtube watch?v=dQw4w9WgXcQ&list=RDdQw4w9WgXcQ&start_radio=1 <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Bart more like Fart <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>wheres the original highway crew <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Aiden is a tranny <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>grief this, bitch! <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>The Youngest Anarchy Server, EVER! - fitmc <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>let me get uhhhhhhhhhh <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>soek eats sand <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><red>i have no idea bruh <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>like 2b2t but just a bit more soft spoken <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>slow children at play <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>ali has a hot sister <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>808 mafia <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>The F students are invetors <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><red> No /tpa no /sethome just pure gay sex <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>?kit <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>nonprofit weed factory <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>all donations go towards toasted avacodos addiction to marijauana <newline><bold><italic><gold><italic>10T"
    - "<blue><bold><italic>10B <reset><yellow>dont feed the griefers <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><dark_red>Repetition is the father of learning. <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Is Fit innocent? <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Stay. <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Ye - HH <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Ye - Cousins <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Try the cactus dupe. <newline><bold><italic><gold>10T <newline><bold><italic><gold>10T"
    - "<blue><bold><italic>10B <reset><yellow>Do Not Fuck The Animals, Thank You! <newline><bold><italic><gold>10T <newline><bold><italic><gold>10T"
